Repository simonmdsn/CrazyCurve, pull requests merged in 2020-04, with the labels that each got.

#35 EraserPowerUp implemented. Erases all tails from all snake.
  Core/src/main/java/sdu/cbse/group2/Game.java
  Core/src/main/java/sdu/cbse/group2/assets/Assets.java
  EraserPowerUp/osgi.bnd
  EraserPowerUp/pom.xml
  EraserPowerUp/src/main/java/sdu/cbse/group2/eraserpowerup/EraserPowerUp.java
  EraserPowerUp/src/main/java/sdu/cbse/group2/eraserpowerup/EraserPowerUpPlugin.java
  EraserPowerUp/src/main/resources/META-INF/eraserpowerupplugin.xml
  LibGDX/src/main/resources/powerup/eraser.png
  collision/osgi.bnd
  pom.xml
Labels: enhancement

#36 Creates tails with processing service instead of a scheduled task. Sh…
  CommonSnake/osgi.bnd
  CommonSnake/src/main/java/sdu/cbse/group2/commonsnake/CommonSnake.java
  CommonSnake/src/main/java/sdu/cbse/group2/commonsnake/Tail.java
  CommonSnake/src/main/java/sdu/cbse/group2/commonsnake/TailProcess.java
  CommonSnake/src/main/resources/META-INF/tailprocessor.xml
  CommonSnake/src/main/resources/readme.txt
  Player/src/main/java/sdu/cbse/group2/player/PlayerPlugin.java
  collision/src/main/java/sdu/cbse/group2/collision/CollisionDetector.java
  pom.xml
Labels: bug, enhancement

#40 Fix ses
  Core/src/main/java/sdu/cbse/group2/Game.java
  Core/src/main/java/sdu/cbse/group2/assets/Assets.java
  Core/src/main/java/sdu/cbse/group2/gamestates/MenuState.java
  Core/src/main/java/sdu/cbse/group2/gamestates/PlayState.java
  Core/src/main/java/sdu/cbse/group2/gamestates/State.java
  Enemy/src/main/java/sdu.cbse.group2.enemy/EnemyPlugin.java
  EraserPowerUp/src/main/java/sdu/cbse/group2/eraserpowerup/EraserPowerUp.java
  EraserPowerUp/src/main/java/sdu/cbse/group2/eraserpowerup/EraserPowerUpPlugin.java
  Player/src/main/java/sdu/cbse/group2/player/PlayerPlugin.java
  collision/src/main/java/sdu/cbse/group2/collision/CollisionDetector.java
  pom.xml
Labels: bug

#55 Bundle naming fix and runtime load/unload settings implementation.
  Common/pom.xml
  CommonSnake/pom.xml
  CommonWeapon/pom.xml
  Core/pom.xml
  Core/src/main/java/sdu/cbse/group2/gamestates/GameStateManager.java
  Core/src/main/java/sdu/cbse/group2/gamestates/MenuState.java
  Core/src/main/java/sdu/cbse/group2/gamestates/PlayState.java
  Core/src/main/java/sdu/cbse/group2/gamestates/SettingsState.java
  Core/src/main/java/sdu/cbse/group2/gamestates/State.java
  Core/src/main/java/sdu/cbse/group2/gamestates/settings/CrazyCurveModule.java
  Core/src/main/java/sdu/cbse/group2/gamestates/settings/SettingsState.java
  Enemy/pom.xml
  LibGDX/pom.xml
  LibGDX/src/main/resources/player/tail.png
  Player/pom.xml
  Weapon/pom.xml
Labels: enhancement

#73 Bug loading modules fix
  Core/src/main/java/sdu/cbse/group2/Game.java
  Core/src/main/java/sdu/cbse/group2/gamestates/MenuState.java
  Core/src/main/java/sdu/cbse/group2/gamestates/settings/SettingsState.java
  LibGDX/src/main/resources/textures/menustate/inputfield.png
  LibGDX/src/main/resources/textures/menustate/quit button.PNG
  LibGDX/src/main/resources/textures/menustate/settings button.PNG
  LibGDX/src/main/resources/textures/menustate/start button.png
  LibGDX/src/main/resources/textures/menustate/title.png
  LibGDX/src/main/resources/textures/settingstate/back button.png
  LibGDX/src/main/resources/textures/settingstate/quit button.png
Labels: bug

#74 Dynamic loading fixes
  CommonSnake/src/main/java/sdu/cbse/group2/commonsnake/CommonSnake.java
  Enemy/src/main/java/sdu.cbse.group2.enemy/EnemyPlugin.java
  EraserPowerUp/src/main/java/sdu/cbse/group2/eraserpowerup/EraserPowerUp.java
  Map/src/main/java/sdu/cbse/group2/map/SnakeTable.java
  Player/src/main/java/sdu/cbse/group2/player/PlayerPlugin.java
  Round/src/main/java/sdu/cbse/group2/round/Round.java
  Round/src/main/java/sdu/cbse/group2/round/spawn/Spawn.java
Labels: bug
